### ISSUE TITLE
Suitable for 3D segmentation

### ISSUE THREAD

**Issue by giovform** [xu-ji/IIC#19]
Hello, thanks for sharing these very nice results and code. It's up and running for some of my data now. I am kinda new to the field of Deep Learning and I was wondering if this method is suitable for 3D segmentation. Would it require too many modifications?

Thank you,

Giovanni

**Comment by xu-ji** [comment]
It could potentially be applied to 3D segmentation. There are a number of ways you could modify our current pipeline. The simplest is just to slice the 3D image into disjoint 2D images and use our method as it currently is. Or you could make the slices overlap, so each point appears in more than one image, and get the average prediction (for more robustness). And/or, try to change the local spatial invariance (which is currently 2D, because it maximises MI between patches and nearby patches in x,y space) into 3D local spatial invariance. The more of these modifications applied, the more I would expect performance to improve.
