### ISSUE TITLE
Memory issue RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by shlokk** [xu-ji/IIC#3]
When I  run on 4 gpus 
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m code.scripts.segmentation.segmentation_twohead --mode IID --dataset Coco164kCuratedFew --dataset_root /vulcan/scratch/shlok/IIC/datasets --model_ind 555 --arch SegmentationNet10aTwoHead --num_epochs 4800 --lr 0.0001 --lamb_A 1.0 --lamb_B 1.5 --num_sub_heads 1 --batch_sz 1 --num_dataloaders 1 --use_coarse_labels --output_k_A 15 --output_k_B 3 --gt_k 3 --pre_scale_all --pre_scale_factor 0.33 --input_sz 128 --half_T_side_sparse_min 0 --half_T_side_sparse_max 0 --half_T_side_dense 10 --include_rgb  --coco_164k_curated_version 6 --use_uncollapsed_loss --batchnorm_track > gnoded1_gpu0123_m555_r1.out

I receive following error. 

File "/vulcan/scratch/shlok/Ana/envs/python2.7pytorch/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/vulcan/scratch/shlok/Ana/envs/python2.7pytorch/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/vulcan/scratch/shlok/IIC/code/scripts/segmentation/segmentation_twohead.py", line 451, in <module>
    train()
  File "/vulcan/scratch/shlok/IIC/code/scripts/segmentation/segmentation_twohead.py", line 216, in train
    using_IR=config.using_IR)
  File "code/utils/segmentation/segmentation_eval.py", line 25, in segmentation_eval
    verbose=verbose)
  File "code/utils/cluster/cluster_eval.py", line 100, in cluster_subheads_eval
    verbose=verbose)
  File "code/utils/cluster/cluster_eval.py", line 160, in _get_assignment_data_matches
    verbose=verbose)
  File "code/utils/segmentation/segmentation_eval.py", line 127, in _segmentation_get_data
    xrange(config.num_sub_heads)]
RuntimeError: CUDA out of memory. Tried to allocate 4.48 GiB (GPU 0; 10.92 GiB total capacity; 6.56 GiB already allocated; 3.77 GiB free; 1.39 MiB cached)

Do you know why this might occur, I have reduced my batch size to 2. 
Also, how many gpu did you use?

**Comment by xu-ji** [comment]
It's occurring in the evaluation. Reducing batch size does not help because currently it needs to store all predictions for all pixels for the dataset in GPU memory. We did this so computing accuracy can occur on the GPU and be fast.

For the segmentation experiments we maxed out our per-machine resources. The particular script you are using was run on 4 Tesla P40 cards with 22.9GB memory each = 91.6GB.

The ways to get by with less GPU memory: 1) change the eval to use CPU rather than GPU memory. This will make eval slower, so also change the script to not eval on every epoch 2) small batch size 3) reduce input image size if you have to.

(Btw the image clustering scripts have much lower memory requirements, maximum of 22.9GB. Output per image is just 1 prediction vector rather than 200x200 prediction vectors.)

**Comment by scott327** [comment]
Sorry for bothering again, 

Recently I have trained the classifier for STL10, and this problem also occurs in my situation. I just use one 16GB - K80, and after turning the batch size smaller(from 700 to 200), it seems that the GPU stops working during the period time of training, which is before the phase of evaluation.

May I ask do you have any advice for training STL10 without resizing the input imge size, or any other advise for making the training run under the condition of simple GPU?

Thank you so much for your support, and really sorry for continuous questions.
