### ISSUE TITLE
classify my images by IIC

### ISSUE THREAD

**Issue by GaGsv** [xu-ji/IIC#37]
hello
thank you for that great work.
i have 38 K images  size 128*128 , and i want to classify them into   7 groups using  your model.
unfortunately i cannot know how i can run your model for this problem , i can say am try all way for that and everything not work.
now i have your code with all package  installed in my machine.
so can you tell me how what i can do .

**Comment by GaGsv** [comment]
note :
All image  dataset unlabeled

**Comment by xu-ji** [comment]
For colour natural images edit a [script](https://github.com/xu-ji/IIC/blob/master/code/scripts/cluster/cluster_sobel_twohead.py) that includes sobel filtering.

You will need to change at least the following things:
- Remove all evaluation from the script, including calls to `cluster_eval`, since you have no labels.
- Replace all calls to `cluster_twohead_create_dataloaders` with a call to your own function, which should work in the same way but load your own data.

Then run the script on the command line, [examples](https://github.com/xu-ji/IIC/blob/master/examples/commands.txt#L18) are included in the repository.
