### ISSUE TITLE
About the local spatial invariance in segmentation loss

### ISSUE THREAD

**Issue by yaochx** [xu-ji/IIC#39]
Hi xuji,
In your paper 3.3 segmentation, in order to build the spatial relationships between patches, you did a convolution within every gt-k layer of prediction. Maybe this will lead to detail loss. The main class in local will dominate the region, is that right? do you have any idea about that?

**Comment by xu-ji** [comment]
We do want some spatial smoothness, in general we do want adjacent pixels to have the same class. But this is not the only thing that is being optimised.

The mutual information objective is optimising for a balance between this smoothness (given by minimising the conditional entropy component between predictions of close pixels) and detail (given by maximising entropy of predictions, which means in every batch every cluster needs pixels assigned to it). The latter means, for example, assigning all pixels to 1 cluster is very suboptimal if there are 10 clusters in total. That is how we preserve detail. By forcing different classes to exist.

For example, in a dataset of trees and roads, if one pixel is tree, and a pixel next to it is road, it may be more optimal to put those pixels in different classes than in the same one. Because although you will get higher conditional entropy since the classes are not the same (bad for loss value), you will also get higher entropy as it makes the global class distribution more uniform (good for loss value). If good > bad, optimising the objective means reinforcing those pixels having different classes. Furthermore at the dataset level, since the network representation is shared and assuming all trees have a similar representation, putting one tree pixel in the same class as the road pixel amounts to encouraging all tree pixels to be in the same class as road pixels. Now, you can see that this may be very suboptimal for the objective, because all the pixels will be assigned to 1 class, meaning entropy is low (bad for loss), even if conditional entropy is low (good for loss). Putting tree and road pixels in different classes may lead to a better loss overall (quite good i.e. high entropy, quite good i.e. low conditional entropy), and this does happen in our datasets because we can see that tree and road pixels are put in different classes.
