### ISSUE TITLE
unsupervised learning vs semi-supervised overclustering

### ISSUE THREAD

**Issue by goldentimecoolk** [xu-ji/IIC#56]
Hi, thanks to your amazing work!
I'm curious about why semi-supervised overclustering (IIC+) could have around 30 percentage higher accuracy than unsupervised learning (IIC) on STL10. Combined with your code and the paper, my personal understanding is:
At training stage, IIC has two heads, A (let's call it overhead whose k is larger than kgt) and B. A and B are trained with 113k and 13k data alternatively. While IIC+ has only one overhead and is trained by 105k data. 
At evaluation stage, IIC directly uses 13k labeled data to get a match for head B and simutaniously calculate the accuracy. But IIC+ uses 5k labeled data to get a match which is further used to calculate the accuracy on 8k data. (So the supervised part for "semi-" dose not modify the trained parameters but find a more accurate match)
From the training stage, the IIC+ seems to be simpler than IIC in both training procedure and data. So the 30 percentage improvement is mainly derived from the evaluation stage where IIC+ has a "better" match than IIC. Is that right? 
Thank you.

**Comment by xu-ji** [comment]
Yes.
Labels are used in the evaluation stage more powerfully in IIC+. IIC+ finds a many-to-one match between many output clusters to few ground truth clusters, IIC finds a 1-1 match between few to few. For IIC, the unsupervised objective has to do 100% of the work of mapping images to clusters, whereas in IIC+ part of this work is done by supervised labels. 

You can also think of it as IIC's evaluation has higher standards. For 3 ground truth classes it needs to learn 1 cluster to detect A, 1 cluster to detect B, 1 cluster to detect C exactly. If a cluster that actually detects A is forced to be assigned to B at evaluation because no cluster detects B, because the network learned to care about images of A but not B during training, class B could easily get ~0% accuracy. Not the case for IIC+, which has many more than 3 clusters, so even if B only gets detected by a small number of clusters, it's unlikely to be 0 clusters.

**Comment by goldentimecoolk** [comment]
I seem to get the essence of over-clustering. Thanks for your detailed explanation.
