### ISSUE TITLE
RGB or BGR format?

### ISSUE THREAD

**Issue by ifeherva** [xu-ji/IIC#59]
In the segmentation transforms custom_greyscale_numpy() uses RGB2GRAY, but opencv opens images by default with BGR. Did I miss a conversion from BGR2RGB somewhere?

https://github.com/xu-ji/IIC/blob/master/code/utils/segmentation/transforms.py#L12

**Comment by xu-ji** [comment]
I think you are right, this affects loading of COCO stuff images which are done with cv2 so are BGR (Potsdam is RGB ordered so is unaffected). But I don't think this has a material effect, since it just means the constants used for turning colour into grey swaps the 0.114, 0.299 weights for red and green. A difference that is further nullified as we sobel filter the greyscale image.

Feel free to correct it in your experiments but I will keep the code here as it is for reproducibility.
