### ISSUE TITLE
Unsupervised Segmentation Loss - conceptual question

### ISSUE THREAD

**Issue by sebastiani** [xu-ji/IIC#6]
Hey, I was reading through the segmentation code and I notice that you utilize the pixel labels in the loss through some sort of mask. Is this really unsupervised, or are you just using that as a prior or filter before computing the loss? Any insights will be appreciated, thanks a lot!

**Comment by xu-ji** [comment]
It's only used to filter the COCO dataset, for discarding our predictions for non-Stuff pixels because we only use the COCO-Stuff part of the COCO dataset. This is because textural "Stuff" is where the local spatial invariance assumption most holds true. It does show some ability to segment non-textural objects (like humans etc.) but not as cleanly.

**Comment by sebastiani** [comment]
Okay, thanks!
