### ISSUE TITLE
About shared parameters

### ISSUE THREAD

**Issue by lucianohps** [xu-ji/IIC#65]
In figure 2 of the paper it's said that
> Dashed line denotes shared parameters

But reading the code I can't find where de parameters of a fully connected layer are shared. ClusterNet6cTrunk doesn't have any linear layer and ClusterNet6cHead's linear layers don't share parameters between them. The same thing happens with ClusterNet5g. Am I missing something here?

**Comment by felizang** [comment]
I have the same question. Your code doesn't seem to share the weights at fully connected layers.
Is it correct?

**Comment by jizongFox** [comment]
The weight is shared between original images and transformed images given a linear head. But the heads for clustering (k=gt_num) and over-clustering are not shared.

**Comment by xu-ji** [comment]
The fully connected layer in each sub-head is not shared with any other sub-head. They are supposed to be different i.e. separate sets of weights. The idea is training all of them gives you resilience against specific malevolent initializations of a sub-head. Training all of them makes you less dependent on any single initialization.

**Comment by xu-ji** [comment]
The sharing of fully connected layers in fig 2 is because both x and augmented x' are run through the same head (and sub-heads within). Sub-heads are missing from this figure i.e. it's showing when there's only 1 sub-head, the simplest case.

To do the sharing, you don't actually create two fully connected layers in the code, you create one and run both images through the same one.

**Comment by felizang** [comment]
Oh, I understand. 
Maybe I was confused because of the name like 'head_A' and 'head_B' in **_two_head.py files.
Then, do head_A and head_B represent the main output head and an auxiliary head?

**Comment by lucianohps** [comment]
Now I get it. Thanks!
