### ISSUE TITLE
Running the code for MNIST 2d pointcloud dataset

### ISSUE THREAD

**Issue by DasNabanita** [xu-ji/IIC#78]
Hi @xu-ji, I am new to this field so please bear with me. I am trying to perform unsupervised IIC on the MNIST 2d point cloud dataset. I have made the necessary changes that you have mentioned in your previous posts for the custom dataset. As transformations, I am only using rotation and translation for now.  
I am extracting the dataset from a .csv file which consists of a label, x-coordinate, and y-coordinate. The dimension of the training set is (60000, 703) and that of the test set is (10000, 703). You have hardcoded the network according to the input_sz. could you please specify the changes to be made to make it work for my dataset.

**Comment by xu-ji** [comment]
How is the "703" dimension split up?

Making IIC work on point clouds is an interesting question, and I think not easy. The simplest thing would be to turn each point cloud into the corresponding 2D or 3D image format and then proceed normally with IIC for images.

I guess the problem with using the raw point cloud format is the index of each element is meaningless (unlike pixels in images), because it's supposed to be an unordered set. Whereas features learned in a neural network latch onto absolute position of values in each input. This problem could be helped, but not overcome entirely, if you sort each point cloud's list of coordinates by x,y position before passing to the network, which would make index more meaningful.

Whether you do sort or not, you would need a network without convolutions like a multi-layer perceptron (fully connected layers only), as convolutions rely on spatial dimensions. It's simple to write one. Also it would be good to normalise the x,y positions into e.g. the range [0, 1] before passing to the network. Input size I suppose would be the number of points * 2, one element each for x and y.

**Comment by DasNabanita** [comment]
Thank you for your reply :)

The dimension is split as (2,351). My aim is to use the points without converting them into an image.  When I read from the .csv file the points are loaded in the order of that is saved in the file. The number of points is 351 for each x and y coordinate, I tried by changing the input size into 2*351 and tried the network as it is, however it fails with an error saying 'RuntimeError: Given input size: (128x1x175). Calculated output size: (128x0x87). Output size is too small'.

My goal is to first segment a 2D point cloud and then categorize those segments into different clusters based on similarity in shapes in an unsupervised manner. You have suggested using a multi-layer perceptron, which is also used in the PointNet. So can I use that instead of the one you have used?

[MNISTPOINTCLOUD.zip](https://github.com/xu-ji/IIC/files/4993118/MNISTPOINTCLOUD.zip)

**Comment by xu-ji** [comment]
> My goal is to first segment a 2D point cloud and then categorize those segments into different clusters based on similarity in shapes in an unsupervised manner

I see, then it's closer to the segmentation case of IIC. What do you specifically want to the network to predict? I.e. what's your desired output dimensions? 

Having decided this, you can in theory use any network architecture that maps your input dimensions onto the desired output dimensions. Probably none of the architectures currently implemented satisfy this, so unsurprising they do not work out of the box. 

I think you will also need to write your own version of the IIC loss function.

**Comment by DasNabanita** [comment]
My actual dataset is not labeled. I want the network to at first segment(in a meaningful way) and then put identical segments into a cluster. I don't know the number of clusters that may result in(i.e. fully unsupervised). Could you please suggest if this can be achieved using IIC loss or in any other direction that might help in solving this problem.

**Comment by DasNabanita** [comment]
Hi @xu-ji, sorry for bothering you again. Could you please explain in what way I need to change the IIC loss function if I want to perform unsupervised clustering. Thank you :)

**Comment by xu-ji** [comment]
I have no idea if this would actually work, but off the top of my head I can see at least 2 options:

1. Let's say the neural network (multi layer perceptron) takes inputs of size (b, 2*351), where the 2nd dimension contains sorted coordinates, and makes outputs with size (b, c, 351), where b is batch size and c is some fixed number of output clusters. The loss function would take the output tensor x of size (b, c, 351) and compute some local-region loss with mutual information. For example, for each b' < b, for each i < 351, get its prediction x[b', :, i], and find the prediction of the closest other point in the same input, i.e. x[b', :, i'] where i' is the index of the closest other point. (Can do this because you know the real coordinates of each of the 351 points). Then, you can maximise mutual information between these two predictions, in the same way we maximise predictions of pairs of images in the paper.

2. Instead of processing each full pointcloud at a time, you could operate on local regions directly. So for each point, get the n closest points. The input to the network is now size (b, 2*(n+1)), and output x is size (b, c). For each b' <b, max mutual information between its prediction x[b', :] and the prediction x[b'', :] where b'' is the index of the input that is geographically the closest to b'. It's another kind of local region loss.
