### ISSUE TITLE
custom dataset

### ISSUE THREAD

**Issue by sc-56** [xu-ji/IIC#80]
Sorry for bothering again, 

thanks so much for providing script to load the custom dataset, and I have one question that if i use the imageFolder to load the image from various classes, the sequence seems really regular and organized.

Do I need to change the sequence and make them distribute ramdomly ilke MNIST/CIFAR, or I can just take the data into your script?

Thank you so much for your help.

**Comment by xu-ji** [comment]
Yes, good point! The data should be shuffled. ImageFolder doesn't. `DataLoader` takes a `sampler` argument where you can specify a deterministic shuffling. Deterministic because the idea is each of the different dataloaders should be sampling the same image in each timestep. I'll try to write a simple deterministic sampler and change the code to use it.

Or you could just set `shuffle=True` for the dataloader. Then it's slightly different from what we did in the paper but may still work.

(I didn't use ImageFolder in any of the original experiments so did not come across this issue.)

**Comment by sc-56** [comment]
Thank you so much for your detailed explanation.

**Comment by xu-ji** [comment]
[I added](https://github.com/xu-ji/IIC/commit/9ae95d1df9fc68755ef6c2fe284f9f779da4f0b4) deterministic shuffling for ImageFolder.

**Comment by sc-56** [comment]
Thank you so much for your support!
