### ISSUE TITLE
How does network keep track of image pairs if one dataloader generates both image and its transformations?

### ISSUE THREAD

**Issue by vivektreddy** [xu-ji/IIC#86]
I am trying to run fully unsupervised cluster without any labels on greyscale image data.  
In the create_basic_clustering_dataloaders function, I see that there is only one dataloader per head.  Each dataloader consists of a dataloader for the original image x and other dataloader(s) for the transformed image.   I am wondering how the network knows which image corresponds to which transformed image.  How will it know between which images to calculate the mutual information?  
Thank you.

**Comment by xu-ji** [comment]
It's because the order of data in each dataloader is the same across them (no shuffling. Or, deterministic/constant shuffling).

So dataloader_0[i] corresponds to dataloader_n[i] for all i and n, where n corresponds to the index for each dataloader with transformed data and i is the index into the length of the data.

**Comment by vivektreddy** [comment]
Sounds good Thank you for the clarification.
