### ISSUE TITLE
Error when trying to run Pretrained STL weights.

### ISSUE THREAD

**Issue by vivektreddy** [xu-ji/IIC#88]
Hi,

I had a question regarding trying to run inference using pretrained weights for fully unsupervised clustering on the STL10 data.
Since STL10 is RGB and I have a greyscale dataset, I tried doing a grayscale to RGB transformation in a simpler dataloader I created.

```
def load_data(config):
    transform = transforms.Compose([transforms.Lambda(lambda x: x.repeat(3, 1, 1)),transforms.ToTensor(),
                                    transforms.Resize(tuple(np.asarray([config.input_sz,config.input_sz])))])
    train_data_path = os.path.join(config.dataset_root, "Crops/")
    dataloader = torch.utils.data.DataLoader(torchvision.datasets.ImageFolder(root=train_data_path, transform=transform),
        batch_size=int(config.batch_sz),shuffle=False,num_workers=0,drop_last=False)
    return dataloader
```
However, when I try to run this code, I get the following error.  
 Unexpected key(s) in state_dict: "head_A.heads.1.0.weight", "head_A.heads.1.0.bias", "head_A.heads.2.0.weight", "head_A.heads.2.0.bias", "head_A.heads.3.0.weight", "head_A.heads.3.0.bias", "head_A.heads.4.0.weight", "head_A.heads.4.0.bias", "head_B.heads.1.0.weight", "head_B.heads.1.0.bias", "head_B.heads.2.0.weight", "head_B.heads.2.0.bias", "head_B.heads.3.0.weight", "head_B.heads.3.0.bias", "head_B.heads.4.0.weight", "head_B.heads.4.0.bias".
        size mismatch for trunk.conv1.weight: copying a param with shape torch.Size([64, 2, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 1, 3, 3]).  

My question is why is the parameter of the checkpoint (64,2,3,3)  Since it is 3 channel, shouldn't it be (64,3,3,3)?  Also, what are the unexpected keys showing up in the state_dict.  Thank you!

**Comment by xu-ji** [comment]
The input to that network has 2 channels because it takes the sobel filtered image. (In the [suppmat](https://github.com/xu-ji/IIC/blob/master/paper/suppmat_camera_ready.pdf) you can find input channel sizes in table 2.)
So I think you don't need to convert to RGB, just sobel filter your greyscale images to get 2 channels.

As for the names, it suggests you are loading my model into a different model template you wrote with your own code. Causing the name mismatch. To avoid this I guess you should load into an instance of the actual class I used. For STL this was [ClusterNet5gTwoHead](https://github.com/xu-ji/IIC/blob/master/examples/commands.txt#L18).

**Comment by vivektreddy** [comment]
OK Thank you for the help. I was not accounting for the 2nd sobel channel.
