### ISSUE TITLE
How to visualize metrics on fully unsupervised clustering for entire dataset?

### ISSUE THREAD

**Issue by vivektreddy** [xu-ji/IIC#90]
After performing unsupervised clustering on all of my image data samples, I would like to use the categorical class labels from ImageFolder to see how well they clustered.  I think accuracy can be obtained from cluster_eval where mapping_test_dataloader == mapping_train_dataloader.  
Do I just set the mapping dataloaders equal to all the data to get the accuracy statistics in stats_dict, and then optionally add in other metrics Im interested in like F1 score, recall, cluster homogeneity, etc?
Thank you!

**Comment by xu-ji** [comment]
Yes that sounds fine.

**Comment by vivektreddy** [comment]
OK thanks.

**Comment by vivektreddy** [comment]
I want to try clustering with different amount of clusters with fixed number of classes to see which clustering looks best, so I am using _original_match, which is many to one.  My understanding of the _original_match is that it finds the match of output label to ground truth label that provides the best possible true positive score.  
Since there are many clusters that will correspond to one label (due to _original_match), how would this work if I wanted to calculate metrics like precision,recall, and F1 score?    Do you need to manually write a function that considers points that are in different clusters but have the same label to be true positives?  Or is there another way that you did this?
Thanks.

**Comment by xu-ji** [comment]
If this is just to get a general idea of how well the model is doing, you can assume the "best case". That is, across all labelled validation data, find the best many-to-one map between output clusters to true labels and transform the model's output using this mapping to see which true label is assigned to each datapoint. Now that the output is in the same domain as true labels you can compute any metric between prediction and target.
I think this is what the code should already do if you use original_match. But it does not count as fully unsupervised metric due to material use of labels.

**Comment by vivektreddy** [comment]
Thank you for the response.  Yes I would like to get a general idea of how well the model is doing by using Silhouette Score, cluster homogeneity, precision, and recall.  

All my images have labels.  However, I don't want all images of the same category to group together. This is because some images in different categories look the same, and I want those to group together.   For example, if I have 10 categories, hopefully I can end up with around 5 or 6 clusters that contain similar looking images.  For this reason, I don't think I should be using accuracy (please correct me if I'm wrong).  Since accuracy would be maximized if the 10 categories were all placed into their own 10 clusters or even more (in many-to-one case)

So for me, I think the "best case" clustering would not necessarily always be the one with the best accuracy.  I think the best case would be to have distinct clusters that all contain similar looking images within themselves but very different from clusters far away from them.  Since I have no labels to determine most similar looking images, I am hoping Silhouette score, homogeneity, precision, and recall will give some good insight into the clustering.  
Is there a simple fix to incorporate precision and recall into the code?  Should I be using the many to one original match to try different amounts of clusters and find the best one?
Thanks a lot for your feedback and insight!

**Comment by xu-ji** [comment]
Sorry for the late reply.

> I am hoping Silhouette score, homogeneity, precision, and recall will give some good insight into the clustering.

Yep, it makes sense to use heuristics for insight. (Those precision and recall scores would of course need to not rely on labels.)

Since you don't have labels I don't think you can use my evaluation code, including the many-to-one mapping, which is found using labels. You need to write your own evaluation code, incorporating the heuristics you have in mind.
